### ISSUE TITLE
Well defined labels are gone

### ISSUE THREAD

**Issue by fabiand** [kubevirt/common-templates#36]
Initially when defining templates (like here https://github.com/kubevirt/common-templates/blob/v0.1.0/templates/rhel75.yaml), it was agreed on a set (actually one) specific label (as defined here https://github.com/kubevirt/kubevirt/blob/master/docs/devel/guest-os-info.md):

```
- apiVersion: kubevirt.io/v1alpha2
  kind: VirtualMachine
  metadata:
    labels:
      kubevirt.io/os: rhel7.5
```

It seems that the `kubevirt.io/os` label which should have a value which is a libosinfo short-id, is gone when looking at a recent release: https://github.com/kubevirt/common-templates/releases/tag/v0.3.1
