### ISSUE TITLE
Create a Template for Generic Linux OS

### ISSUE THREAD

**Issue by prabhulc** [kubevirt/common-templates#576]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST
> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:
I'd like to provision a virtual machine using a template suitable for a generic operating system. However, upon reviewing the common templates available, I couldn't find one specifically designed for this purpose.

**What you expected to happen**:
It would be beneficial to include a generic template or explore alternative options to accomplish provisioning a virtual machine with a generic operating system.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):  Client Version: version.Info{GitVersion:"v1.2.0",Server Version: version.Info{GitVersion:"v1.1.1-78-gfc124cfdd" 
- Kubernetes version (use `kubectl version`): Server Version: v1.28.7+c1f5b34
- common-templates version: 0.28.0
- VM or VMI specifications: 
- Cloud provider or hardware configuration: Openshift
- OS (e.g. from /etc/os-release):
-NAME="Red Hat Enterprise Linux CoreOS"
ID="rhcos"
ID_LIKE="rhel fedora"
VERSION="415.92.202403270524-0"
VERSION_ID="4.15"
VARIANT="CoreOS"
VARIANT_ID=coreos
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 415.92.202403270524-0 (Plow)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::coreos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://docs.openshift.com/container-platform/4.15/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.15"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.15"
OPENSHIFT_VERSION="4.15"
RHEL_VERSION="9.2"
OSTREE_VERSION="415.92.202403270524-0"

- Kernel (e.g. `uname -a`): Linux 00-50-56-99-9a-59 5.14.0-284.59.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Mar 19 09:41:26 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
![image](https://github.com/kubevirt/common-templates/assets/31506656/f340f20d-d232-49c5-97e7-a9f527c36f20)
In KVM there is an option to select Generic when import existing disk image option.

**Comment by 0xFelix** [comment]
I'm not sure about the usefulness of a generic template. What settings would you include that differ from a bare `VirtualMachine`? What boot source should the template require?

**Comment by 0xFelix** [comment]
Maybe an `InstanceType` without `Preference` would be more beneficial to your needs?

https://github.com/kubevirt/common-instancetypes

**Comment by prabhulc** [comment]
Hi @0xFelix , Thank you for replying.

I would like to boot this OS (SS attached)
![image](https://github.com/kubevirt/common-templates/assets/31506656/0e01d55c-fbd0-431a-b927-67479c176daf)

For this KVM image to function properly, it requires an OS template that is generic. I've confirmed its functionality within KVM. However, upon migration to Openshift virtualization, I couldn't find a corresponding option for a generic OS template

**Comment by prabhulc** [comment]
![image](https://github.com/kubevirt/common-templates/assets/31506656/a77b3f43-11ad-48fd-a3ad-35a6d17ea11c)

**Comment by 0xFelix** [comment]
My point is, what would you like to see in a generic template? A template contains OS specific settings and points to a specific boot source. Can't you create a template yourself for this use case or alternatively just use a plain `VirtualMachine` pointing to your boot volume?

**Comment by prabhulc** [comment]
I attempted to create a plain VirtualMachine, but it booted into the dracut shell instead. I'm new to this and uncertain if I made a mistake. (Screenshot and vm.yaml attached)
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:    
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1    
  generation: 1
  labels:
    app: generic-vm-8
    app1: morp    
  name: generic-vm-8
  namespace: default  
spec:  
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small        
      creationTimestamp: null
      labels:
        kubevirt.io/domain: generic-vm-8
        kubevirt.io/size: small
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 8
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          inputs:
          - bus: virtio
            name: tablet
            type: tablet
          interfaces:          
          - masquerade: {}
            model: virtio
            name: default
          logSerialConsole: false
          networkInterfaceMultiqueue: true
          rng: {}        
        memory:
          guest: 24Gi
        resources: {}
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: generic-vm8-pvc
        name: rootdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: generic-vm
            password: kubeops
            chpasswd: { expire: False }
        name: cloudinitdisk

```

![image](https://github.com/kubevirt/common-templates/assets/31506656/83722b4b-40ef-4ea9-b2c9-88393a452966)
